### ISSUE TITLE
Are the apks work with your S8, S8+ or Note 8?

### ISSUE THREAD

**Issue by ChristophGeske** [ChristophGeske/ARCoreInsideOutTrackingGearVr#1]
I am not sure if the apks work with the S8, S8+ or Note 8. Please share your experiences if you have one of those devices.

**Comment by dabrodev** [comment]
I have tested the "room" and "trivial" scenes with S8 and it works only as normal VR app, no tracking. The default HelloAR working correctly.

**Comment by ChristophGeske** [comment]
I encounter the same issue on my phone (S7) before. The GearVR is loading the game just fine but the positional tracking doesn't work. I suspect that the ARCore is stopping in the background for some unknown reason. Simply restarting the phone helped. It's also nessesary to install the arcore-preview2.apk (https://developers.google.com/ar/develop/downloads) to make the head tracking work.

**Comment by ChristophGeske** [comment]
I just uploaded an ARCore v1.0.0 version and it was reported to work with the Note 8. I assume S8, S8+ are also supported now.
