### ISSUE TITLE
whiteisland.apk built with wrong name and no launch icon

### ISSUE THREAD

**Issue by tr0043t** [ChristophGeske/ARCoreInsideOutTrackingGearVr#12]
The current whiteisland.apk appears to have been built with the name com.VRWizard.WhiteIsland and while it can be signed there is no obvious way to launch it since after installation there is no launch icon, though the app does appear in the Android installed app list in settings.

**Comment by ChristophGeske** [comment]
Yes I can reproduce the bug and already know how to fix it. Will do it as soon as possible.

**Comment by tr0043t** [comment]
Thanks much!
