### ISSUE TITLE
followARCoreCamera - correct the script filename

### ISSUE THREAD

**Issue by tomekkie** [ChristophGeske/ARCoreInsideOutTrackingGearVr#21]
followARCoreCamera - correct the filename (first letter to capital), because the script doesn't load, and the built app doesn't work as supposed.
The same issue with antialisingCorrection.cs

**Comment by ChristophGeske** [comment]
Thanks my git settings where not set to being case sensitive.
"git config core.ignorecase false" should solve the issue in the future.
