### ISSUE TITLE
Missing Prefabs in Unity Project

### ISSUE THREAD

**Issue by jessekirbs** [ChristophGeske/ARCoreInsideOutTrackingGearVr#29]
Hello, I'm trying to open the BoxyCardboard Unity project. I get an initial error stating that is was made with an earlier version of Unity, and then when I open it there are lots of missing prefabs. Any ideas how to fix this? Thank you!

**Comment by ChristophGeske** [comment]
This is a common problem with new Unity versions not supporting projects build with an older Unity version. 
What you need to do is first to check which Unity version the project was built with. You find a ProjectVersion.txt file in the ProjectSettings folder as explained here (
https://answers.unity.com/questions/845575/how-to-know-unity-version-of-an-unity-project-with.html )

Than you need to download and install the Unity version you see in the ProjectVersion.txt file and I think you also need to re-unpack the project again and start it fresh with the correct Unity version. You might be fine with installing a slightly newer version let's say the project was build with Unity 2018.1 and you install Unity 2018.4 but when you try to use a 2018.1 build project with Unity 2019.x you likely get those strange errors.

This is not very user friendly in my opinion to be required to install a different Unity Version for each project but you are now in the developer area and here functionality is more important than user friendliness I guess.
