### ISSUE TITLE
Why Are There Oculus Go .apks?

### ISSUE THREAD

**Issue by Lukas1h** [ChristophGeske/ARCoreInsideOutTrackingGearVr#33]
Why are there Oculus Go .apks if the Oculus Go 1) does not have ARCore and 2) does not have a camera to use for tracking?
Am I missing something?

**Comment by Heath123** [comment]
> The Oculus GO has no camera so there is no head tracking possible, but because the high-quality environment scene captured with the Seurat tool could be interesting for Go users as well, I added controller support so that flying through the scene by pressing the touchpad is possible.

**Comment by Lukas1h** [comment]
Ah, I see. Thanks for the info.
